// TEMA_FV_U8: Puesta a tierra y protecciones en FV (67 preguntas - IDs 18001-18067)
// Incluye 10 preguntas de EXAMEN OFICIAL integradas

const TEMA_FV_U8_DATA = [
  {id: 18001, tema: 18, texto: "EPI significa: (TEST OFICIAL)", opciones: ["Equipo de protección inmediata", "Equipo de protección individual", "Equipo de puesta inmediata", "Equipo de paseo individual"], correctaTexto: "Equipo de protección individual", explicacion: "EPI: casco, guantes, arnés, gafas, botas seguridad. Obligatorio en trabajos electricidad/altura. Cada trabajador responsable su EPI."},
  {id: 18002, tema: 18, texto: "Es un elemento de protección en instalaciones industriales: (TEST OFICIAL)", opciones: ["Móvil", "Señalización", "Cinta adhesiva", "Todas las afirmaciones son correctas"], correctaTexto: "Señalización", explicacion: "Protección colectiva: señalización riesgo (advertencia, obligación), vallas, iluminación, señales acústicas. Elemento previo a EPI individual."},
  {id: 18003, tema: 18, texto: "Señala cual no es un riesgo en la ejecución de una instalación fotovoltaica en la cubierta de una vivienda: (TEST OFICIAL)", opciones: ["Trabajo en altura, riesgo de caída a distinto nivel", "Riesgo eléctrico", "Riesgo en el uso de útiles y herramientas", "Riesgo de envenenamiento"], correctaTexto: "Riesgo de envenenamiento", explicacion: "Riesgos FV cubierta: altura (caída), eléctrico (paneles generan DC), herramientas (cortes), golpes. NO hay riesgo envenenamiento (no hay químicos tóxicos normalmente)."},
  {id: 18004, tema: 18, texto: "Señala cuál no es un accesorio que nos otorgue protección: (TEST OFICIAL)", opciones: ["Guantes aislantes", "Reloj", "Calzado laboral de seguridad", "Tapones o cascos antirruido"], correctaTexto: "Reloj", explicacion: "EPI: guantes aislantes (eléctrico), calzado seguridad (impacto), casco antirruido (ruido). Reloj: NO es EPI de protección."},
  {id: 18005, tema: 18, texto: "Para trabajos en baja tensión (1000Vca y 1500Vdc) en los que se pudiera estar en contacto con tensión, se emplearán guantes de Clase: (TEST OFICIAL)", opciones: ["0", "4", "2", "66"], correctaTexto: "2", explicacion: "Guantes clase 2: hasta 17kV. Para BT (1000V): clase 0 (500V) es insuficiente, clase 2 (17kV) asegura. Clase 4: hasta 36kV (eléctrica alta tensión)."},
  {id: 18006, tema: 18, texto: "Las señales de advertencia tienen el fondo de color: (TEST OFICIAL)", opciones: ["Amarillo", "Rojo", "Azul", "Blanco"], correctaTexto: "Amarillo", explicacion: "Colores señalización: amarillo (advertencia), rojo (peligro/parada), azul (obligación), verde (seguridad). Norma ISO 3864."},
  {id: 18007, tema: 18, texto: "Las señales de obligación llevan el fondo de color: (TEST OFICIAL)", opciones: ["Blanco", "Rojo", "Amarillo", "Azul"], correctaTexto: "Azul", explicacion: "Señales obligación (usar casco, guantes): fondo azul + símbolo blanco. Ejemplo: 'USE CASCO OBLIGATORIO'."},
  {id: 18008, tema: 18, texto: "Los tipos de contacto entre una persona y la corriente son: (TEST OFICIAL)", opciones: ["Inalámbrico y por contacto directo", "Por choque y por rozadura", "Contacto directo e indirecto", "Contacto indefinido y definido"], correctaTexto: "Contacto directo e indirecto", explicacion: "Directo: toque de conductor activo (alto riesgo). Indirecto: toque de masa metálica defectuosa (tierra protege). Diferencial previene indirecto."},
  {id: 18009, tema: 18, texto: "Se deberá trabajar sin tensión en la instalación para evitar situaciones de riesgo. Una de las fases para garantizar el trabajo sin tensión será impedir la reconexión, ¿cómo se realizaría esta fase?: (TEST OFICIAL)", opciones: ["Bastará con comunicarlo a parte de los usuarios de la instalación", "Se instalará un candado, pasador o elemento de señalización que impida la reconexión a la red", "No es necesario realizar ninguna actuación, se trabajará de forma habitual", "Ninguna respuesta es correcta"], correctaTexto: "Se instalará un candado, pasador o elemento de señalización que impida la reconexión a la red", explicacion: "Bloqueo desconexión: candado + cartel 'NO CONECTAR' durante trabajo. Previene reconexión accidental/malintención. Obligatorio en trabajos tensión."},
  {id: 18010, tema: 18, texto: "Si se realiza una instalación fotovoltaica en una cubierta inclinada con línea de vida. Señala que equipo de protección se deberá emplear obligatoriamente para este trabajo en altura: (TEST OFICIAL)", opciones: ["Guantes Aislantes Clase 4", "Protectores Auditivos", "Arnés de Seguridad", "Pantalla de protección facial"], correctaTexto: "Arnés de Seguridad", explicacion: "Trabajo altura: arnés obligatorio (máximo 6m sin línea, >6m con línea). Conectar línea vida. Otros EPI (guantes, casco) también pero arnés es crítico caída."},
  {id: 18011, tema: 18, texto: "¿Cuál es la 'Resistencia de Puesta a Tierra' máxima para instalación FV?", opciones: ["Sin límite", "< 100 Ω típico (varía según ubicación y tensión)", "> 1000 Ω", "No existe límite legal"], correctaTexto: "< 100 Ω típico (varía según ubicación y tensión)", explicacion: "Resistencia tierra < 100 Ω. Zonas rocosas requieren múltiples electrodos. Medición anual obligatoria con telurómetro."},
  {id: 18012, tema: 18, texto: "¿Qué es la 'Puesta a Tierra de Protección'?", opciones: ["Conectar salida paneles a tierra", "Conectar masas metálicas a electrodo dispersor para limitar tensión contacto < 50V", "Solo en días lluviosos", "No necesaria en FV"], correctaTexto: "Conectar masas metálicas a electrodo dispersor para limitar tensión contacto < 50V", explicacion: "Protección: si masa defectuosa lleva 230V, tierra la remite, diferencial dispara < 30mA. Límite seguridad: 50V CA / 120V DC."},
  {id: 18013, tema: 18, texto: "¿Cuál es el 'Diferencial de Alta Sensibilidad' recomendado en FV?", opciones: ["100 mA", "30 mA (clase A o B para corrientes CA/pulsante)", "1 A", "Sin especificar"], correctaTexto: "30 mA (clase A o B para corrientes CA/pulsante)", explicacion: "Diferencial 30mA: límite Reglamento. Algunos inversores generan corrientes DC residuales → diferenciales tipo B (detectan DC). Importante verificar compatible."},
  {id: 18014, tema: 18, texto: "¿Qué es el 'Interruptor de Corriente de Defecto' (RCD)?", opciones: ["Un regulador", "Dispositivo que detecta corriente de fugas (defecto aislamiento) y desconecta", "Un inversor", "Inexistente"], correctaTexto: "Dispositivo que detecta corriente de fugas (defecto aislamiento) y desconecta", explicacion: "RCD (Residual Current Device) = Diferencial. Compara corriente entrada/salida. Si diferencia > 30mA (fuga a tierra), dispara < 200ms. Elemento crítico seguridad."},
  {id: 18015, tema: 18, texto: "¿Cuál es la 'Tensión de Contacto Máxima Permitida'?", opciones: ["100V", "50V CA / 120V DC (límite seguridad)", "230V (sin límite)", "1000V"], correctaTexto: "50V CA / 120V DC (límite seguridad)", explicacion: "Norma: < 50V CA ó < 120V DC son 'extra baja tensión' (muy baja riesgo). > 50V requiere protecciones (diferencial, tierra)."},
  {id: 18016, tema: 18, texto: "¿Qué es un 'Defecto de Aislamiento'?", opciones: ["Falta de aislante", "Pérdida continuidad aislamiento (fuga corriente a masa/tierra); detectado por diferencial", "Fallo pintura", "No existe"], correctaTexto: "Pérdida continuidad aislamiento (fuga corriente a masa/tierra); detectado por diferencial", explicacion: "Defecto aislamiento: cable dañado, componente con derivación a masa. Diferencial lo detecta (fuga típica 1-10mA). Medidor aislamiento verifica (>100kΩ)."},
  {id: 18017, tema: 18, texto: "¿Cuál es el 'Factor de Seguridad' en fusibles?", opciones: ["Sin factor", "1.25-1.5× Isc (sobrecarga asegurada, no falsos disparos)", "3×", "5×"], correctaTexto: "1.25-1.5× Isc (sobrecarga asegurada, no falsos disparos)", explicacion: "Fusible = 1.25 × Isc. Si Isc 12A, fusible 15A. Evita disparos innecesarios por variaciones irradiancia, mantiene protección cortocircuito."},
  {id: 18018, tema: 18, texto: "¿Qué es un 'Conductor de Protección' (PE)?", opciones: ["Conductor activo", "Conductor verde-amarillo conecta masas metálicas a tierra; cero potencial eléctrico", "Conductor neutro", "Opcional"], correctaTexto: "Conductor verde-amarillo conecta masas metálicas a tierra; cero potencial eléctrico", explicacion: "PE (Protective Earth): no lleva corriente normal, solo en caso defecto aislamiento. Código color: verde-amarillo rayado. Presencia obligatoria en todas instalaciones > 48V."},
  {id: 18019, tema: 18, texto: "¿Cuál es la 'Distancia Mínima de Seguridad' cerca de líneas eléctricas aéreas?", opciones: ["0 metros (contacto permitido)", "1 metro horizontal, 3-5 metros vertical según voltaje línea", "10 metros", "50 metros"], correctaTexto: "1 metro horizontal, 3-5 metros vertical según voltaje línea", explicacion: "Distancia seguridad líneas aéreas: 1m horizontal, 3m vertical BT, 5m AT. Instalación FV debe respetar. Coordinación con distribuidora obligatoria."},
  {id: 18020, tema: 18, texto: "¿Qué es un 'Descargador de Sobretensión' (SPD) tipo 2?", opciones: ["Protección primaria", "Protección secundaria instalada en armario distribución; derivación sobretensiones a tierra", "Solo decorativo", "No existe"], correctaTexto: "Protección secundaria instalada en armario distribución; derivación sobretensiones a tierra", explicacion: "SPD tipo 1: entrada instalación. SPD tipo 2: armario. SPD tipo 3: final circuito. Coordinación coordina descarga sobretensiones (onda rayo 6kV+ → tierra segura)."}
];
